import type { SlidePlan } from "@/lib/ds/schema";

export const samplePlan: SlidePlan = {
  title: "Idempotency di API: Retry yang Aman",
  caption: "Kenapa retry aman kalau API-mu idempotent.\n\nSimpan biar nggak lupa!",
  hashtags: ["backend", "api", "idempotency", "vourdev"],
  slides: [
    {
      role: "cover",
      eyebrow: "BACKEND 101",
      headline: "Idempotency itu wajib",
      accentWord: "Idempotency",
      lede: "Biar retry nggak bikin data dobel, konsep yang wajib lo ngerti, bukan cuma hafal.",
    },
    {
      role: "point",
      counter: "02 / 08",
      eyebrow: "TERM",
      headline: "Pecah istilahnya",
      accentWord: "istilahnya",
      body: "Idempotency dibentuk dari beberapa ide inti yang saling nyambung.",
      mockup: {
        type: "concept",
        parent: "Idempotency",
        children: ["Key", "Retry", "Dedupe", "State"],
        note: "Idempotency = request sama, hasil satu.",
      },
    },
    {
      role: "point",
      counter: "03 / 08",
      eyebrow: "ALUR",
      headline: "Jalannya request",
      accentWord: "request",
      body: "Retry masuk ke jalur yang sama; key bikin server kenal duplikat.",
      mockup: {
        type: "flow",
        steps: [
          { label: "Client" },
          { label: "API", focus: true },
          { label: "Dedupe" },
          { label: "DB" },
        ],
        note: "Dedupe nyaring key yang sama.",
      },
    },
    {
      role: "point",
      counter: "04 / 08",
      eyebrow: "CONTOH",
      headline: "Pakai Idempotency-Key",
      accentWord: "Idempotency-Key",
      body: "Kirim key unik per aksi; server nolak duplikat dengan key yang sama.",
      mockup: {
        type: "terminal",
        filename: "charge.ts",
        lines: [
          { text: "// key unik per aksi", style: "cmt" },
          { text: "await pay(order, {", style: "plain" },
          { text: "  idempotencyKey: uuid()", style: "key" },
          { text: "})", style: "plain" },
        ],
      },
    },
    {
      role: "point",
      counter: "05 / 08",
      eyebrow: "EKOSISTEM",
      headline: "Simpan state di mana",
      accentWord: "state",
      body: "Server nyimpen key yang sudah diproses di salah satu store ini.",
      mockup: {
        type: "hub",
        center: "Key store",
        tools: [
          { icon: "database", label: "Postgres" },
          { icon: "zap", label: "Redis" },
          { icon: "cloud", label: "DynamoDB" },
        ],
        note: "Pilih yang cepat & tahan lama.",
      },
    },
    {
      role: "point",
      counter: "06 / 08",
      eyebrow: "SALAH VS BENAR",
      headline: "Jangan retry buta",
      accentWord: "buta",
      body: "Retry tanpa key bikin dobel; dengan key aman diulang.",
      mockup: {
        type: "comparison",
        loserLabel: "Tanpa key",
        loserLine: "2× charge ke kartu user",
        winnerLabel: "Dengan key",
        winnerLine: "Charge kedua di-skip server",
        winnerRationale: "Server ingat key yang sudah diproses.",
      },
    },
    {
      role: "point",
      counter: "07 / 08",
      eyebrow: "RECAP",
      headline: "Yang lo dapat",
      accentWord: "dapat",
      body: "Ringkasan biar gampang diinget.",
      mockup: {
        type: "checklist",
        items: [
          "Retry itu normal",
          "Idempotency-Key per aksi",
          "Server dedupe by key",
          "Retry jadi aman",
        ],
        note: "Simpan biar nggak lupa.",
      },
    },
    {
      role: "outro",
      eyebrow: "KESIMPULAN",
      headline: "Bikin retry aman",
      accentWord: "aman",
      body: "Idempotency = request sama, hasil tetap satu.",
      cta: {
        strong: "Simpan & bagikan",
        sub: "Backend & dev-education tiap minggu di @vourdev.",
      },
    },
  ],
};
