import type { SlidePlan } from "@/lib/ds/schema";

export const samplePlan: SlidePlan = {
  title: "Idempotency di API — Retry yang Aman",
  caption: "Kenapa retry aman kalau API-mu idempotent.\n\nSimpan biar nggak lupa!",
  hashtags: ["backend", "api", "idempotency", "vourdev"],
  slides: [
    {
      role: "cover",
      eyebrow: "BACKEND 101",
      headline: "Idempotency itu wajib",
      accentWord: "Idempotency",
      lede: "Biar retry nggak bikin data dobel — konsep yang wajib lo ngerti, bukan cuma hafal.",
    },
    {
      role: "point",
      counter: "02 / 07",
      eyebrow: "KENAPA",
      headline: "Retry itu normal",
      accentWord: "Retry",
      body: "Network gagal, client ngulang request. Tanpa jaminan, satu aksi kejadian dua kali.",
      mockup: { type: "card", icon: "repeat", title: "Retry-safe", body: "Request sama → hasil sama.", tone: "peach" },
    },
    {
      role: "point",
      counter: "03 / 07",
      eyebrow: "CONTOH",
      headline: "Pakai Idempotency-Key",
      accentWord: "Idempotency-Key",
      body: "Kirim key unik per aksi; server nolak duplikat dengan key yang sama.",
      mockup: {
        type: "terminal",
        filename: "charge.ts",
        lines: [
          { text: "// key unik per aksi", style: "cmt" },
          { text: "await pay(order, {", style: "plain" },
          { text: "  idempotencyKey: uuid()", style: "key" },
          { text: "})", style: "plain" },
        ],
      },
    },
    {
      role: "point",
      counter: "04 / 07",
      eyebrow: "SALAH VS BENAR",
      headline: "Jangan andalkan retry buta",
      accentWord: "buta",
      body: "Retry tanpa key bikin dobel; retry dengan key aman diulang.",
      mockup: {
        type: "comparison",
        loserLabel: "Tanpa key",
        loserLine: "2× charge ke kartu user",
        winnerLabel: "Dengan key",
        winnerLine: "Charge kedua di-skip server",
        winnerRationale: "Server ingat key yang sudah diproses.",
      },
    },
    {
      role: "point",
      counter: "05 / 07",
      eyebrow: "CARA PAKAI",
      headline: "Tiga langkah aman",
      accentWord: "Tiga",
      body: "Pola minimum biar endpoint-mu idempotent.",
      mockup: {
        type: "steps",
        items: [
          { title: "Generate key", body: "UUID per aksi di client." },
          { title: "Kirim di header", body: "Idempotency-Key: <uuid>." },
          { title: "Simpan hasil", body: "Cache respons per key." },
        ],
      },
    },
    {
      role: "point",
      counter: "06 / 07",
      eyebrow: "DAMPAK",
      headline: "Kurangi error dobel",
      accentWord: "dobel",
      body: "Efek nyata di produksi setelah endpoint dibuat idempotent.",
      mockup: { type: "bigstat", number: "0", unit: "dobel", caption: "Charge ganda hilang saat retry." },
    },
    {
      role: "outro",
      eyebrow: "KESIMPULAN",
      headline: "Bikin retry aman",
      accentWord: "aman",
      body: "Idempotency = request sama, hasil tetap satu.",
      cta: {
        strong: "Simpan & bagikan",
        sub: "Backend & dev-education tiap minggu di @vourdev.",
      },
    },
  ],
};
