// One-off/codegen: emit lib/ds/icons.generated.ts with inline <svg> strings for
// a curated allowlist, sourced from the installed lucide-react (authentic paths).
// Fails loudly if any slug is missing — the allowlist is strict by construction.
import { writeFileSync } from "node:fs";

const SLUGS = [
  "terminal", "server", "database", "key", "shield-check", "lock",
  "git-branch", "code", "cpu", "network", "cloud", "zap", "repeat",
  "arrow-right", "alert-triangle", "check-circle", "x-circle", "circle-alert",
  "sparkles", "layers", "box", "workflow", "timer", "gauge", "bug", "wrench",
  "rocket", "book-open", "lightbulb", "target", "trending-up", "file-code",
  "braces", "webhook", "refresh-cw", "folder",
];

// Some friendly slugs are deprecated re-export shims in lucide-react v1.24 (no
// own __iconNode). Keep the friendly name as the allowlist key, but source the
// SVG path data from the canonical icon file.
const ALIAS = {
  "alert-triangle": "triangle-alert",
  "check-circle": "circle-check",
  "x-circle": "circle-x",
};

// lucide default SVG envelope (matches lucide-react createLucideIcon defaults).
const OPEN =
  '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" ' +
  'viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" ' +
  'stroke-linecap="round" stroke-linejoin="round">';

function childToTag([tag, attrs]) {
  const a = Object.entries(attrs)
    .filter(([k]) => k !== "key") // React-only, not valid SVG
    .map(([k, v]) => `${k}="${v}"`)
    .join(" ");
  return `<${tag} ${a}/>`;
}

const entries = [];
for (const slug of SLUGS) {
  const sourceSlug = ALIAS[slug] || slug;
  const url = new URL(
    `../node_modules/lucide-react/dist/esm/icons/${sourceSlug}.mjs`,
    import.meta.url
  );
  let mod;
  try {
    mod = await import(url.href);
  } catch {
    throw new Error(`lucide-react has no icon "${slug}" — fix the allowlist`);
  }
  const node = mod.__iconNode;
  if (!Array.isArray(node) || node.length === 0) {
    throw new Error(`icon "${slug}" has empty __iconNode`);
  }
  const svg = OPEN + node.map(childToTag).join("") + "</svg>";
  entries.push([slug, svg]);
}

const slugsLiteral = SLUGS.map((s) => `"${s}"`).join(", ");
const svgLines = entries
  .map(([slug, svg]) => `  "${slug}": String.raw\`${svg}\`,`)
  .join("\n");

const ts = `// AUTO-GENERATED by scripts/gen-icons.mjs — do not edit by hand.
// Inline lucide SVGs for the carousel icon allowlist. Committed so rendering has
// no runtime dependency and no network (preview + PNG export both work offline).
export const ICON_SLUGS = [${slugsLiteral}] as const;

export const ICON_SVGS: Record<string, string> = {
${svgLines}
};
`;

writeFileSync(new URL("../lib/ds/icons.generated.ts", import.meta.url), ts);
console.log(`✅ wrote lib/ds/icons.generated.ts (${entries.length} icons)`);
